################################################################################

# This Makefile generated by GoMakeGen 0.8.0 using next command:
# gomakegen .

################################################################################

.DEFAULT_GOAL := help
.PHONY = fmt all clean deps help

################################################################################

all: redis-monitor-top ## Build all binaries

redis-monitor-top: ## Build redis-monitor-top binary
	go build redis-monitor-top.go

install: ## Install binaries
	cp redis-monitor-top /usr/bin/redis-monitor-top

uninstall: ## Uninstall binaries
	rm -f /usr/bin/redis-monitor-top

deps: ## Download dependencies
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v pkg.re/essentialkaos/ek.v9

fmt: ## Format source code with gofmt
	find . -name "*.go" -exec gofmt -s -w {} \;

clean: ## Remove generated files
	rm -f redis-monitor-top

help: ## Show this info
	@echo -e '\nSupported targets:\n'
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[33m%-12s\033[0m %s\n", $$1, $$2}'
	@echo -e ''

################################################################################
